version: "3"
services:
  mongodb-client:
    image: 'mongo'
    container_name: mongodb-client
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - mongodb-client:/data/db/client
    # environment: 
    #   - MONGODB_USERNAME=user
    #   - MONGODB_PASSWORD=password
    networks:
      backend:

  client-micro:
    build:
      context: ./ 
    restart: always
    # image: diegotony/client-micro:travis
    ports:
      - "4003:4003"
    environment:
      - MONGO_HOST=mongodb-client
      - PORT=4003
    depends_on:
      - mongodb-client
    links:
      - mongodb-client
    networks:
      backend:

volumes:
  mongodb-client:
networks:
  backend:
    driver: bridge